Repository sourcecred/docs, pull requests merged in 2020-11, with the labels that each got.

#228 Update Beta Plugin Docs “discord”
  docs/beta/plugins/discord.md
Labels: netlify-cms/pending_publish

#230 Update Beta Plugin Docs “discord”
  docs/beta/plugins/discord.md
Labels: netlify-cms/pending_publish

#233 docs: freshen `cred.md` and `grain.md`
  docs/beta/cred.md
  docs/beta/grain.md
Labels: refinement

#235 Update Beta Docs “setup-guide”
  docs/beta/setup-guide.md
Labels: netlify-cms/pending_publish

#244 Reorder FAQ page contents
  docs/beta/FAQ.md
Labels: netlify-cms/pending_review

#248 Update Beta Docs “FAQ”
  docs/beta/FAQ.md
Labels: netlify-cms/draft
