Repository sourcecred/docs, pull requests merged in 2020-07, with the labels that each got.

#128 Update Blog “2020-05-11-version-0.5.0-released”
  blog/2020-05-11-version-0.5.0-released.md
Labels: netlify-cms/pending_publish

#133 Create Main “best-resources-for-new-contributors”
  docs/FAQ.md
  docs/best-resources-for-new-contributors.md
Labels: netlify-cms/pending_review

#129 Setup Search Functionality
  docusaurus.config.js
  package.json
  yarn.lock
Labels: tooling

#134 Create Main “our-calls”
  docs/our-calls.md
Labels: netlify-cms/draft

#122 First draft of the setup guide
  docs/setup-guide.md
Labels: netlify-cms/pending_review

#135 Create Main “our-platforms”
  docs/our-platforms.md
Labels: netlify-cms/pending_review
