Repository sourcecred/docs, pull requests merged in 2020-08, with the labels that each got.

#176 Update Beta Docs “FAQ”
  docs/beta/FAQ.md
Labels: netlify-cms/draft

#156 Update Beta Docs “setup-guide”
  docs/beta/setup-guide.md
Labels: netlify-cms/pending_review

#162 Update Beta Docs “grain”
  docs/beta/grain.md
  static/img/uploads/grain-token-icon.png
Labels: netlify-cms/pending_publish

#161 Update Beta Docs “cred”
  docs/beta/cred.md
Labels: netlify-cms/pending_publish

#144 Update Beta Docs “our-calls”
  docs/beta/our-calls.md
Labels: netlify-cms/pending_publish

#145 Update Beta Docs “our-platforms”
  docs/beta/our-platforms.md
Labels: netlify-cms/pending_publish

#186 Update Beta Docs “setup-guide”
  docs/beta/setup-guide.md
Labels: netlify-cms/pending_publish

#178 Update Beta Docs “get-involved”
  docs/beta/get-involved.md
Labels: netlify-cms/pending_publish

#194 Update Beta Docs “cred”
  docs/beta/cred.md
Labels: netlify-cms/pending_publish

#195 Update Beta Docs “get-involved”
  docs/beta/get-involved.md
Labels: netlify-cms/pending_publish
